Complete second endpoint, passing tests
tanzil-eth/be-nc-games pull request #2
Opened 2023-02-21 15:45 UTC by tanzil-eth

2023-02-21 16:10 UTC, Augs0 requested changes
Hey Tanzil, great attempt on this but there are quite a things to change or that are missing so please revisit this ticket and look at the comments I have left here

2023-02-21 16:10 UTC, Augs0 commented on __tests__/app.test.js
> +					title: "Agricola",
We don't wanna check specific data here in case it changes. Instead, we can check the properites and data types of the values :)

2023-02-21 16:10 UTC, Augs0 commented on controllers/reviews-controller
> +const selectReviews = require("../models/reviews-models");
I think this file doesn't have a .js at the end of it?

2023-02-21 16:10 UTC, Augs0 commented on __tests__/app.test.js
> +	});
Something else we are missing here is that reviews should contain their comment count too. We could achieve this with a join in our query

2023-02-21 16:10 UTC, Augs0 commented on __tests__/app.test.js
> +});
We also need to another test that checks that the default order is descending, created_at

2023-02-21 16:59 UTC, Augs0 requested changes
Almost there now 👍 well done! Just a few more things to change. Please see the feedback

2023-02-21 16:59 UTC, Augs0 commented on __tests__/app.test.js
> +				const sortedReviews = reviews.sort((a, b) => {
We don't need to do this if we use jest-sorted. Consider adding this package to make things a bit easier for you testing wise

2023-02-21 16:59 UTC, Augs0 commented on __tests__/app.test.js
> +						})
We should expect a number here. You will need to explore how to change the data type in your query

2023-02-22 11:50 UTC, Keb84 approved these changes
Nice additions Tanzil. Ready to merge 🙂

2023-02-22 11:51 UTC, merged